language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10' # Have to use v10 for async generators
script:
  - yarn test
  - yarn build
matrix:
  allow_failures: []
  fast_finish: true
after_success:
  - npx ci-scripts github-post
  - npx ci-scripts slack
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
